### ISSUE TITLE
To Do List

### ISSUE THREAD

**Issue by npmccallum** [mbestavros/enarx-modular-tests#1]
- [ ] Move `misc-lints-clippy-all` to a lint step for all repos
- [ ] Move `misc-lints-missing-docs` to a lint step for all library repos
- [ ] Drop `misc-licenses-crate`
- [ ] Convert `misc-consistent-linked-issues` to a GHA
- [ ] Drop `cargo-toml-package-license`
- [ ] Drop `cargo-toml-package-edition`

**Comment by mbestavros** [comment]
As we've now decided to not pursue `misc-lints-clippy-all` and `missing-docs`, and `consistent-linked-issues` has become `[link-your-issues`](https://github.com/mbestavros/link-your-issues), I think it's fair to consider this done.
